
jenkins:
  systemMessage: "Configured as Code"

credentials:
  system:
    domainCredentials:
      - credentials:
          - basicSSHUserPrivateKey:
              scope: GLOBAL
              id: jenkins-github-ssh
              username:
              passphrase:
              description: "SSH key for GitHub"
              privateKeySource:
                directEntry:
                  privateKey: ${JENKINS_GITHUB_SSH}

unclassified:
  globalConfigFiles:
    configs:
      - json:
          id: auth-json
          name: auth.json
          comment: from jcasc
          content: ${JENKINS_AUTH_JSON}

jobs:
  - script: >
      job('super-seed') {
        scm {
          git {
            remote {
              url ('https://github.com/tpeltone/configuration-as-code-jenkins-k8s-jobdsl.git')
              credentials('jenkins-github-ssh')
            }
          }
        }
        steps {
          dsl {
            external('jobdsl/**/*.groovy')
            removeAction('DELETE')
          }
        }
      }

security:
  globaljobdslsecurityconfiguration:
    useScriptSecurity: false
